version: "3.9"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-web-app
    ports:
      - "5173:5173"
    volumes:
      - .:/
      - /node_modules
    stdin_open: true
    tty: true
